export const posts = [
  {
    post: `Introduction

With the vast development of machine learning techniques, the use of artificial intelligence (AI) has been a rising trend in the labour market for the past few decades. Artificial intelligence is set to influence every aspect of our lives as it’s capable of process huge amounts of data intelligently, automate tasks previously performed by labour or create new tasks and activities in which humans can be productively employed (Acemoglu & Restrepo 2019). The research by Gartner (2019) shows that the number of enterprises implementing artificial intelligence to their businesses is rising year by year. 37 percent of the organizations across all industries have implemented artificial intelligence in some form in 2019 (Gartner 2019). To shed some light on the incredibly fast implementation of artificial intelligence, according to Gartner (2019) the number of enterprises that implemented AI in 2015 was 10 percent – which makes it 270 percent growth in four years. 

The numbers do not lie, and it is clear that artificial intelligence alongside automation are expected to have an impact in the economy, society and labour as 14 percent of the global workforce needing to change their occupational categories by 2030 due to technological advances (Mujtaba & Mahapatra 2019). The artificial intelligence is going to change all the industries, but in this paper, my focus in solely on what is the role of the artificial intelligence in Human Resource Management (HRM) and in the recruitment process. In the following chapters I will introduce the concept of artificial intelligence and then I move forward to make an understanding on its role in the field of recruiting and human resource management. Last, I will make a statement on how it is going to change that industry of human resource management and wrap up the essay with conclusions on the topic. 
What is artificial intelligence?

In the big picture the term of artificial intelligence can be used on intelligent machines, software or algorithms that can act intelligently and learn by themselves recognizing and responding to their environment (Acemoglu & Restrepo 2020). The term “intelligently” is the most important part when one is defining artificial intelligence because that is the very quality that separates machine agents running artificial intelligence algorithms from the regular algorithms or software.  

Kok et al. (2009) concluded artificial intelligence to the concept that machines can be improved to assume some capabilities normally thought to be like human intelligence such as learning, adapting and self-correction. This conclusion takes us back to the term intelligence. Learning, adapting and self-correction are in the core of what makes us humans intelligent, and artificial intelligence algorithms are designed to mimic those features with the difference that computers can process vast amounts of data at once compared to human brains. 

In a nutshell, even when artificial intelligence can be understood as artificially intelligent systems, most of the definitions can be classified in four categories: systems that can think like humans, systems that act like humans, systems that think rationally and systems that act rationally. (Kok et al. 2009.) Advancements in the field of technology and automation has already changed or replaced some of the traditional repetitive tasks, for instance in the 50s and 60s when automation changed the factory work, when machines were able to produce some of the products and do some of the tasks that humans used to do by hand (Alasoini 2019, 235). Alasoini (2019) states that the advancements in machine learning has made the artificial intelligence machine agents more capable to change and replace some of the non-repetitive tasks, when they are able to dig in the tacit knowledge of human beings as they are able to learn from current, past and future data of the work processes. 

As artificial intelligence and machine learning algorithms advance and alongside them different industries can use their potential to increase productivity and replace some of the tasks that are currently done by humans and humans only, it is safe to say that artificial intelligence is going to change the field of work. As machines and automation previously changed mostly the repetitive tasks, it is predicted that the change in work in the time of artificial intelligence is going to reach the so-called upper levels, the expert work as well (Alasoini 2019, 237). Thus, the change is going to be even bigger – bigger than we have had in the history of human. 
Artificial intelligence in human resource management and recruiting

Now, after the definition of artificial intelligence and a brief introduction on how it is going to change the way of work across all industries, it is time to take a look on the sole focus on this paper – what is the role of artificial intelligence in human resource management and recruiting today. Human resources are the main asset of nations and in the core for achieving prosperity, especially in a time and age, where the competition between organizations to acquire qualified and highly skilled human resources are accelerating (Hmoud & Laszlo 2019, 22). Thus, human resource management (HR or HRM) are under constant pressure to make the process of recruitment more and more effective. 

Traditionally, from human resource management it takes vast amounts of time-consuming repetitive tasks to find suitable candidates in the process of recruitment. These tasks include sourcing and screening the candidates, schedule coordination and communication with the candidate during the recruitment. It has been concluded that utilizing artificial intelligence in the human resource management has promising results to increase productivity and quality by optimizing the talent acquisition. However, as a result some of the administration jobs will be replaced by artificial intelligence machine agents and will gradually disappear. (Hmoud & Laszlo 2019; Upadhyay & Khandelwal 2018.)

Next, I will move on to more detailed description on what is the actual role of the artificial intelligence in HR right now, and how could it affect the field of HR in the future. 
The role of artificial intelligence in recruiting

Artificial intelligence is making some of the processes in the recruitment obsolete, as the usage of the artificial intelligence powered recruiting software is rising in the industry. The recruiters are happy to delegate these repetitive tasks that I mentioned previously to the software, so they could focus more on more sophisticated tasks in recruiting (Upadhyay & Khandelwal 2018, 255). It might raise some eyebrows to think how the machine could replace human in these processes. Next, I will introduce three main artificial intelligence powered functions are already being used in the process of recruitment. 

First off, the possibility of data mining is making data gathering for the recruiters a lot easier. Artificial intelligence powered systems can gather huge amounts of data at once and analyse it with precision. It helps the screening process as the software can scan multiple data sources such as social media sites, resumes and other candidate related sources such as resumes. With advanced text recognition in the screening process, the automated software can cluster and classify talents on how they are presenting themselves. With data mining, it is also possible to scan social media sites and different hiring platforms to search potential candidates that are passive applicants.  The program analyses the gathered data against job specifications and can notify the passive applicants for the opportunity if it finds a potential talent. (Hmoud & Laszlo 2019, 24) 

Secondly, for deeper analysis some of the artificial intelligence hiring software are utilizing artificial neural networks (ANN). In short, the ANN relies in machine learning and it aims to simulate human learning by capturing some of the features of the human nervous system. (Hmoud & Laszlo 2019, 24.) It works hand in hand with the data mining process because the more data the machine learning algorithm get, the more intelligent they become. Thus, it is used in the screening process as well. Hmoud and Laszlo (2019, 24) presented few examples where in one of them the ANN was utilised to score different candidates as it was screening for future managerial talent and in the other ANN was used to discover implicit knowledge of the potential talent to process results that could be used to predict their future performance in the job and in supporting their allocation to suitable projects within the organization.  

Lastly, the most time-consuming part of the recruitment is sourcing because selecting potential talent from a large number of candidates as the recruiters have to go through hundreds or even thousands of applications in the sourcing process to find potential talent. This is also a part of recruitment process where the data mining and ANN are shining outclassing humans. With the advanced text recognition abilities, the artificial intelligence program can learn all the job attributes and automatically review and classify the applications based on that knowledge. It can make the screening process more objective and therefore reduce or even neutralize human bias. (Hmoud & Laszlo 2019; Upadhyay & Khandelwal 2018) 

During the screening process, the candidates find it frustrating that the contact from the human resource management can take up to weeks after applications. With the help of the artificial intelligence recruitment software and specially the chatbots this frustration can be minimized. Chatbots can communicate in real time during the recruitment process. For instance, after the algorithm has evaluated the candidate, it can notify it with affirmative or rejection message within 24 hours of the receipt of application so they can either accept the position or continue with their job search seamlessly. (Upadhyay & Khandelwal 2018) 

It is quite safe to say that the artificial intelligence powered systems are outshining humans in some of the processes in the recruitment. The current usage is focusing on improving recruitment process from both perspectives. It makes the recruitment more efficient for the human resource management and for the candidates as it can provide feedback and communication in real time. The replacement effect of the use of artificial intelligence sounds inevitable, but there are more than what meets the eye. In the next section I will dig deeper in the ethical part of the artificial intelligence in human resource management and recruiting.
Ethics of an artificial intelligence in recruiting

When looking at the ethics of artificial intelligence implementation in the recruiting process the most important part is related to the decision-making, especially when the artificial intelligence software is doing the processes mentioned above autonomously. Piano (2020) states that the decision-making algorithms will always be based on a formal system, which is a representation of a real system and it will be based on restricted set of relevant relations, causes and effects. Even the most complicated algorithms represent one-specific vision of the system being modelled.  

Alongside the one-specific vision of the system, the set of rules that determine the decision-making process are made from human-assumptions (Piano 2020). This is because the artificial intelligence systems cannot work without machine learning that are utilising training data sets to be intelligent. These training data sets are not objective, as they represent previous models that organization has been using in their recruitment process. Ahmed (2018, 975) states that algorithms learn from the past, and if the current management practices in the organization are biased, discriminatory, punitive or overly hierarchical, there is a possibility that these kind of biases gets institutionalized.  

So, the artificial intelligence recruiting software has many ethical dimensions that needs to be taken account if the organizations human resource management wants its recruitment process to be fair to all individuals. There are few precedents that confirms that human biases can carry over to the algorithms if the training sets are not properly set up and the artificial intelligence software remains as a black box to the stakeholders. For instance, in 2017 Amazon used artificial intelligence powered candidate evaluation tool, and as a conclusion the algorithm discriminated female candidates because the training data had under representation of female applicants (Mujtba & Mahapatra 2019). 

Another ethical viewpoint is that how the use of AI-powered systems can influence the behaviour inside the organization because there is a risk of data exposure and inadvertent misuse. Alongside analysing the potential candidates, the human resource management may use artificial intelligence to analyse current talent inside the organization as well. One of the common uses of these analytics are to predict performance of the employees. As an example, if the analytics conclude that one high performer is on a verge to leave the company, and the HR section provides these results to the management, it may affect the communication economy inside the organization. This person may be treated differently based on the conclusion that the AI-system has made autonomously. (Ahmed 2018, 976) 

One way to resolve some of the ethical problems is transparency of the machine learning algorithms. Many authors, including Piano (2020) and Ahmed (2018), have stated that it is vital for machine learning algorithms to be transparent if they have real world consequences by doing decisions autonomously. For instance, in human resource management it is important that the decision-making process can be tracked down. It benefits both parties; the employer has exact information if the process is biased in some way and have the accurate statistics of why the chosen candidates has been picked by the artificial intelligence. Employees could also benefit from transparency, because the feedback from the decision-making process could lead them either to find another kind of job that suits their talents or develop their skills further. 

Piano (2020, 6) is referring to the concept of governance by numbers, where quantification is replacing the traditional decision-making system and profoundly affecting the pillar of equality of judgement. This issue is highly present in the human resource management industry, and if the artificial intelligence algorithms are wrongly implanted it could lead to ethical problems that I stated previously. The algorithms could be restricted and locked down to increase transparency, so they would be more predictable. However, with this strategy the algorithms would become defective if compared to the machine learning processes where we simply cannot know what the algorithms are doing tomorrow because they are constantly learning (Piano 2020, 6). 

There is a solution to this if the stakeholders and developers would come together to make the artificial intelligence good. By good, I mean by mitigating the possible biases in the algorithms and making it fair to all candidates. Piano (2020, 6) suggests that the issue of unpredictable algorithms could be tackled by hard-coding the set of rules on the behavior of the algorithms once these rules are agreed upon among the stakeholders. That could set a good and fair ground for the algorithms and prevent any conflicts with the standards agreed upon the parties involved.  
Will artificial intelligence take over the human resource management industry?

It goes without saying that as the artificial intelligence keeps developing further using it will be the new norm in the human resource management industry, and future generations will see the current ways of screening and sourcing candidates obsolete. The new ways where utilizing artificial intelligence could lead to more productive and accurate recruiting are inevitable as the competition of harvesting the best talent tightens between the organizations. 

However, the human touch is still needed for now. Even when artificial intelligence is changing the nature of competition in the recruitment industry by impacting all the top three priorities like revenue, profitability and candidate acquisition (Upadhyay & Khandelwal 2018, 257). Mujtaba and Mahapatra (2019) stated that for now there are not many artificial intelligence powered systems that could replace interview processes, because research has shown in-person interviews have a better success rate than offline interviews. 

The machines lack human empathy and ability to interact with other human beings in a meaningful way where the recruiter gets to know the candidate personally (Ahmed 2018, 978). These intuitive skills in conversations could lead to more successful recruitments, and it is one of the features that we humans are better when compared to artificial intelligence that mostly looks at the data and makes the decisions based on that. So, when an organization is using artificial intelligence powered systems as part of their recruitment process a right mix between the machine and human needs to be planned. Upadhyay and Khandelwal (2018, 256) state in their article that where artificial intelligence is good at identifying talent, the need of human touch is still present in the activities of recruitment process. These activities include rapport building, assessment of cultural fit and negotiation needs.  

All in all, artificial intelligence is making the recruitment process more productive by identifying talent from huge masses of data. Understanding and interpreting this knowledge is where the human touch is needed. The mundane repetitive tasks will be replaced by artificial intelligence and as a result people in the field of human resource management could focus more on the sophisticated tasks and strategic matters of the job. It is inevitable that artificial intelligence is replacing some tasks in human resource management, but it is not replacing all the jobs within the industry. 
Conclusion

The benefits of using artificial intelligence are becoming so vital in economy where the competition between organizations, states and countries are getting tighter. Optimizing the recruitment process using artificial intelligence is something that is getting more and more attention within the business sector as the ways of machine learning and artificial intelligence are improving. However, how they are utilised in the recruitment process is something that could make or break the whole industry. 

Authors like Ahmed (2018) and Piano (2020) are stating that the transparency of the algorithms and collectively agreed standards in decision-making could be the answer for more fair use of the artificial intelligence in the recruitment process. Also, as the use of artificial intelligence is getting more and more common in the human resource management and recruitment the more sophisticated ways of using artificial intelligence like audio, image and video recognition needs more attention when it comes to research (Mujtaba & Mahapatra 2019). To find suitable methods to mitigate the biases in these areas is necessary. 

In line with Alasoini (2019, 237), it is true that the replacement effect of the artificial intelligence is not covering the whole jobs, rather the effect is going to be real within the jobs and tasks that they include. As the artificial intelligence gets more common and it replaces more and more tasks within different jobs, the division of labour needs reorganizing measures. 

The need for research is vital to understand the change and interpret it in a way that the artificial intelligence would be used as a tool to delegate the tasks that they are currently good at, and let us human beings focus more on the tasks where we outshine machines. In human resource management, the reorganizing measures within the tasks in recruiting cannot be done without proper training and education because if the humans are interpreting the data from artificial intelligence, they need to understand how the decision-making process is done. This also sets demands for the development as the decision-making process should be transparent for the algorithms to be fair and unbiased.  `,
  },
];
